<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * @file
 */


/**
 * Implements hook_mail().
 */
function dt_request_form_mail($key, &$message, $params) {
    $options = array(
        'langcode' => $message['langcode'],
    );

    switch ($key) {
        case 'submit_function':
            $config = \Drupal::config('dt_request_form.collect_email.settings');
            $from_mail  = (empty($config->get('email')) ? \Drupal::config('system.site')->get('mail') :  $config->get('email'));
            \Drupal::logger('dt_request_form')->notice('Submit mail.' . $from_mail,
                []  );
            $message['from'] = $from_mail;
            $message['subject'] = t('Submit mail ', $options);
            $message['body'][] = $params['message'];
            break;
    }
}